# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-21 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=30)),
                ('the_id', models.CharField(max_length=30)),
                ('realname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=30)),
                ('weixin', models.CharField(max_length=30)),
                ('create_time', models.CharField(max_length=30)),
                ('update_time', models.CharField(max_length=30)),
                ('last_login', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('industry', models.CharField(max_length=30)),
                ('investAmount', models.CharField(max_length=30)),
                ('fields', models.CharField(max_length=30)),
                ('stages', models.CharField(max_length=30)),
                ('roles', models.CharField(max_length=30)),
            ],
        ),
    ]
