# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-21 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investorBp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='uid',
        ),
    ]
