# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-22 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investorBp', '0002_remove_investor_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='ps',
            field=models.TextField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
